<template>
    <main class="container">
        <h2>About SARS-CoV-2 </h2>
        <p>SARS-CoV-2, the virus that causes COVID-19, can spread from person to person through droplets produced during coughing or breathing during close contact with an infected individual. Infection can also occur indirect contact when these droplets land on objects and surfaces around the infected individual and the other person touches these objects or surfaces, then touches their eyes, nose or mouth. This is why it is important to stay at least 1-2 meters (3-6 feet) away from a person who is sick. Given that some individuals have no symptoms while still infected with the virus, physical distancing of 1-2 meters should be observed regardless of whether the other person seems sick.</p>
        <h2>What are the symptoms of COVID-19?</h2>
        <p>The most common symptoms of COVID-19 are fever, cough and fatigue. Some patients may have loss of taste or smell, conjunctivitis, headache, muscle aches and pains, nasal congestion, runny nose, sore throat, diarrhea, nausea or vomiting, and different types of skin rashes. These symptoms are usually mild and begin gradually. Some people become infected but don’t develop any symptoms and don't feel unwell. Most people (about 80%) recover from the disease without needing special management. Approximately 1 out of every 6 people who get COVID-19 becomes seriously ill and develops symptoms of severe COVID-19, which include difficulty breathing/shortness of breath, confusion, loss of appetite, persistent pain or pressure in the chest, and needs hospitalization. Older people and those with underlying medical problems like high blood pressure, heart problems or diabetes are more likely to develop serious illness. People with fever, cough and difficulty breathing should seek medical attention.</p>
        <h2>How do I know if it is COVID-19 or just the common cold?</h2>
        <p>A COVID-19 infection has similar signs and symptoms as the common cold or influenza, and you can only differentiate them through laboratory testing to determine the virus type.</p>
        <h2>Can the virus that causes COVID-19 be transmitted through the air?</h2>
        <p>Studies to date suggest that the virus that causes COVID-19 is mainly transmitted through respiratory droplets rather than through the air. See previous answer on “How does COVID-19 spread?” Aerosols may be generated during certain medical procedures and other activities, such as singing, but are not considered the predominant route of spread for this infection.</p>
        <h2>What can I do to protect myself and prevent the spread of disease?</h2>
        <p>☑ Clean your hands regularly and thoroughly with an alcohol-based hand rub or wash them with soap and water. Washing your hands with soap and water or using alcohol-based hand rub kills viruses that may be on your hands.</p>
        <p>☑ Maintain at least 1-2-meter (3-6 feet) distance between yourself and anyone who is coughing or sneezing. When someone coughs or sneezes, they spray small liquid droplets from their nose or mouth which may contain virus. If you are too close, you can breathe in the droplets, including the COVID-19 virus if the person coughing or sneezing has the disease.</p>
        <p>☑ Follow physical distancing rules of at least 1-2-meter (3-6 feet) distance between yourself and others regardless of whether they are showing symptoms.</p>
        <p>☑ Avoid touching your eyes, nose and mouth. Hands touch many surfaces and can pick up viruses. Once contaminated, your hands can transfer the virus to your eyes, nose or mouth. From there, the virus can enter your body and can make you sick.</p>
        <p>☑ Make sure you and the people around you follow good respiratory hygiene. This means covering your mouth and nose with your bent elbow or tissue when coughing or sneezing, then disposing of the used tissue immediately. Droplets spread virus. By following good respiratory hygiene, you protect the people around you from viruses such as the common cold, flu and COVID-19.</p>
        <p>☑ Stay home if you feel unwell. If you have a fever, cough and difficulty breathing, seek medical attention and call in advance. Follow the directions of your local health authority. National and local authorities will have the most up to date information on the situation in your area. Calling in advance will allow your health care provider to quickly direct you to the right health facility. This will also protect you and help prevent spread of viruses and other infections.</p>
        <p>☑ Wear a mask for the duration of your illness and while you have symptoms.as source control to prevent onward spread of COVID-19 if you are infected.</p>
        <p>☑ Wear a mask as part of the comprehensive public health measures targeted to prevent the spread of COVID-19 even if you do not have symptoms and/or are not infected.</p>
        <p>☑ Keep up to date on the latest COVID-19 hotspots (cities or local areas where COVID-19 is spreading widely). If possible, avoid traveling to those places – especially if you are an older person or have diabetes, heart or lung disease, because you have a higher chance of catching COVID-19 in one of these areas.</p>
    </main>
</template>